[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/b3e3e393c77e35a4a3f3cbd1e429b5dc/32/64x64.png"
title = "Cyberpunk 2077"
subtitle = "100+ hrs"

[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/460295ce15c9440d9be6fb474387a285/32/64x64.png"
title = "No Man's Sky"
subtitle = "100+ hrs"

[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/9357e8d9b96de4920a57ba55651c5687/32/64x64.png"
title = "Hell Let Loose"
subtitle = "100+ hrs"

[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/8399caac6d7e6240600ace476e2c83e7/32/64x64.png"
title = "Days Gone"
subtitle = "60+ hrs"

[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/d6140c51d9f0507b9a747e63e335be7d/32/64x64.png"
title = "Disco Elysium"
subtitle = "60+ hrs"

[[collection]]
type = "entry"
icon = "https://cdn2.steamgriddb.com/icon/d50bd39fbde1ad92dcc753562cfd5ef3/32/64x64.png"
title = "Still Wakes the Deep"
