[[collection]]
type = "art"
img = "https://upload.wikimedia.org/wikipedia/en/4/43/Cover_of_Mothership_RPG.png"
title = "Mothership"
subtitle = "Tuesday Knight Games"
content = "Mothership has changed me. I was unfortunately very late to the world of TTRPGs, but very thankful this was my first step. Bathed in the spirit of OSR and the mythos of Alien and Event Horizon, Mothership throws you into the depths of space without a towel..."
footer = "Survive, Solve, Save. Choose One."

[[collection]]
type = "art"
img = "https://www.indiepressrevolution.com/xcart/image.php?type=P&id=23285"
title = "Moonbase Blues"
subtitle = "Anodyne Printware"
content = "A one-shot for the Mothership RPG. This served as the first game I wardened (DM'd) and will last in my memory for a long time. A wonderful compact mystery horror, a moonbase overtaken by an azure aura."
footer = "Warning: may induce color related trauma"

[[collection]]
type = "art"
img = "https://img.itch.zone/aW1hZ2UvMTYzMjI2NC8xNTM4NzIwMC5qcGc=/original/VxOoyO.jpg"
title = "Cloud Empress"
subtitle = "Worlds by Watt"
content = "Although I have yet to run a game with this ruleset spun off of Mothership's Panic Engine, I am already absorbed into the imaginative world of the Hereafter. I cannot wait to dive in."
