[[collection]]
content = 'The Vorrh stretches imagination until, as Terry Gilliam says, “it hurts.” That fearless strangeness keeps my sense of wonder sharp, so the book earns a permanent place on my list.'
type = "art"
img = "https://upload.wikimedia.org/wikipedia/en/f/f9/The_Vorrh.jpg"
title = "The Vorrh"
subtitle = "B. Catling"

[[collection]]
type = "art"
img = "https://m.media-amazon.com/images/I/611K5bSE15L._AC_UF1000,1000_QL80_.jpg"
title = "Eye, Film and Camera in Color Photography"
subtitle = "R. Evans"
content = "Evan's cutting insight and wit on the topic of photography is unmatched. The clarity with which he presents the topic and his wholistic perspective makes me envy anyone that studied or worked with him. I can only hope to be half the genius he was."

[[collection]]
type = "art"
img = "https://upload.wikimedia.org/wikipedia/commons/f/f3/TheOpenBoat.jpg"
title = "The Open Boat"
subtitle = "S. Crane"
content = "This is a work that I thankfully happened upon in a garage sale. Its short but deeply cutting narrative immediately pulled me in, and left me with a long lasting memory of nature's unrelenting force."
