[[collection]]
type = "entry"
link = "https://www.strollswithmydog.com/"
title = "Strolls With My Dog"
subtitle = "Jack Alma"

[[collection]]
type = "entry"
link = "https://www.photonstophotos.net/"
title = "Photons to Photos"
subtitle = "William Claff"

[[collection]]
type = "entry"
link = "https://www.opencolorio.org/"
title = "OpenColorIO"
subtitle = "ASWF"

[[collection]]
type = "entry"
link = "https://cinematiccolor.org/"
title = "Cinematic Color"
subtitle = "Jeremy Selan"
